# Server port
server.port=8082

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/MOU
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Spring Boot logging
# JWT properties
jwt.secret=mySuperSecretKeymySuperSecretKey123456
jwt.expiration=3600000
# Google OAuth2
google.clientId=mou-486906
google.clientSecret=209705114849
logging.level.org.springframework=INFO
logging.level.com.example.demo=DEBUG

